[package]
name = "state_propogator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.7"

[dev-dependencies]
float-cmp = "0.9.0"